### PR TITLE
Add serviceType configuration parameters to uplink docs

### PR DESCRIPTION
**Pull request by welteki**
## Description

Add serviceType helm configuration parameters to the uplink docs.

## Motivation and Context

Keep the chart configuration docs up to date with changes to the chart.

## How Has This Been Tested?

Verified table is rendered locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
> Verified locally.

Expand on this please?

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Do customers have to set the nodePort manually when opting for that?

With OpenFaaS, we default it in.

**Comment by welteki** [comment]
> Do customers have to set the nodePort manually when opting for that?

Pushed an addition to mention the nodePort is assigned automatically when left empty.

**Review by alexellis — APPROVED** [review]
LGTM

**Pull request merged**
